# Generated by Django 4.0.10 on 2023-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worship', models.CharField(max_length=30, verbose_name='Places of Worship')),
                ('community', models.CharField(max_length=30, verbose_name='Community Centres')),
                ('museum', models.CharField(max_length=30, verbose_name='Museums & Art Galleries')),
                ('walking_node', models.CharField(max_length=30, verbose_name='Other Walking Nodes')),
                ('park_node', models.CharField(max_length=30, verbose_name='Other Park Nodes')),
            ],
        ),
    ]
