# Generated by Django 4.0.10 on 2023-07-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userpref_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='park',
            field=models.CharField(default=' ', max_length=30, verbose_name='Parks'),
            preserve_default=False,
        ),
    ]
