# Generated by Django 4.0.10 on 2023-07-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default=' ', max_length=50, primary_key=True, serialize=False, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
