# Generated by Django 4.0.10 on 2023-07-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_email_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='community',
            field=models.CharField(max_length=200, null=True, verbose_name='Community Centres'),
        ),
    ]
