# Generated by Django 4.2.2 on 2023-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_userpref_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpref",
            name="community",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Community Centres"
            ),
        ),
    ]
