name: Code Quality and Compliance

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt flake8 isort

    - name: Check Python code quality
      run: |
        flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        isort backend --check-only --diff

    - name: Setup Node.js for JavaScript checks
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install JavaScript dependencies
      run: |
        npm install

    - name: Check JavaScript code quality
      run: |
        npx eslint src --fix
